name: Feature Request
description: Request a new feature
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - mobile
        - web
        - backend
        - database
        - ml-ai
  - type: textarea
    id: notes
    attributes:
      label: Notes
